FaceFox/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
]

app/urls.py
from django.urls import path 
from . import views
from .views import DetailMs,Inbox
from django.contrib.auth.views import LoginView, LogoutView
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
	path('inicio/',views.inicio, name = 'inicio'),

	path('register/', views.register, name='register'),
	path('',LoginView.as_view(template_name='login.html'), name='login'),
	path('logout/',LogoutView.as_view(), name='logout'),
	path('delete/<int:post_id>', views.delete,name='delete'),
	path('deleteComent/<int:post_id>', views.deleteComent,name='deleteComent'),
	path('like/<int:post_id>', views.like,name='like'),
	path('likeComentario/<int:comentario_id>', views.likeComentario,name='likeComentario'),
	path('comentario/<int:post_id>', views.comentario,name='comentario'),
	
	path('editarPost/<int:pk>',views.editarPost,name='editarPost'),
	path('profile/<str:username>',views.profile,name='profile'),
	path('editar/',views.editar,name='editar'),
	path('follow/<str:username>',views.follow,name='follow'),
	path('unfollow/<str:username>',views.unfollow,name='unfollow'),
	path('Buscar/',views.Buscar,name='Buscar'),
	path('Busqueda/',views.Busqueda,name='Busqueda'),

	
	path('ms/<str:username>',DetailMs.as_view(),name='detailMs'),
	path('',Inbox.as_view(),name="inbox"),


] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)








'''
Para hacer el login solo hay que importar las vistas y 
crear las urls y nos digirimos a settings y se llaman las urls

59895009508
'''

app/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.db.models.signals import post_save
import os
import uuid
from django.db.models import Count
from django.apps import apps
from django.conf import settings
# Create your models here.

class Profile(models.Model):
	user = models.OneToOneField(User, on_delete = models.CASCADE)
	bio = models.CharField(default='Hola Fox', max_length = 20)
	telefono = models.IntegerField(null=True)
	image = models.ImageField(default='imag.png')
	pais = models.CharField(null = True,max_length = 20)
	city = models.CharField(null = True,max_length = 20)

	def __str__(self):
		return f'{self.user.username}'
		
	def following(self):
		user_ids = Relationship.objects.filter(from_user=self.user)\
							.values_list('to_user_id',flat=True)
		return User.objects.filter(id__in=user_ids)

	def followers(self):
		user_ids = Relationship.objects.filter(to_user=self.user)\
							.values_list('from_user_id',flat=True)
		return User.objects.filter(id__in=user_ids)

	

class Post(models.Model):
	timestamp = models.DateTimeField(default=timezone.now)
	content = models.CharField(null=True, blank=True, max_length=30)
	image = models.ImageField()
	likes = models.ManyToManyField(User, related_name="likes")
	user = models.ForeignKey(User, on_delete=models.CASCADE,related_name='posts')

	def delete(self,*args,**kwargs):
		if os.path.isfile(self.image.path):
			os.remove(self.image.path)
		super(Post,self).delete(*args, **kwargs)

	class Meta:
		ordering = ['-timestamp']

	def __str__(self):
		return f'{self.content } -  - -  {self.user}'


#comentarios
class Comentario(models.Model):
	hora = models.DateTimeField(default=timezone.now)
	contenido = models.CharField( max_length=150)
	user = models.ForeignKey(User, on_delete=models.CASCADE,related_name='comentario')
	postCom = models.ForeignKey(Post, on_delete=models.CASCADE,related_name='postCom')
	likes = models.ManyToManyField(User, related_name="likesComentario")

	class Meta:
		ordering = ['-hora']

	def __str__(self):
		return f'{self.contenido }'




class Relationship(models.Model):
	from_user = models.ForeignKey(User, related_name='relationship', on_delete=models.CASCADE)
	to_user = models.ForeignKey(User, related_name='related_to', on_delete=models.CASCADE)

	def __str__(self):
		return f'{self.from_user} a {self.to_user}'

	class Meta:
		indexes = [
		models.Index(fields=['from_user','to_user',]),
		]




#funcion para cuando se cree un usuario crear un perfil(signals)
def crear_perfil(sender, instance, created,**kwargs):
	if created:
		Profile.objects.create(user=instance)

post_save.connect(crear_perfil,sender=User)



#chat ***************************************


class ModelBase(models.Model):
	id = models.UUIDField(default=uuid.uuid4, primary_key=True, db_index=True, editable=False)
	tiempo = models.DateTimeField(auto_now_add=True)
	actualizar = models.DateTimeField(auto_now_add=True)
	
	class Meta:
		abstract = True


class CanalMensaje(ModelBase):
	canal = models.ForeignKey("Canal", on_delete=models.CASCADE)
	usuario = models.ForeignKey(User,on_delete=models.CASCADE)
	texto = models.TextField()

class CanalUsuario(ModelBase):
	canal = models.ForeignKey("Canal",null=True, on_delete=models.SET_NULL)
	usuario = models.ForeignKey(User,on_delete=models.CASCADE)


class CanalQuerySet(models.QuerySet):

	def solo_dos(self):
		return self.annotate(num_usuarios = Count("usuarios")).filter(num_usuarios=2)

	def solo_uno(self):
		return self.annotate(num_usuarios = Count("usuarios")).filter(num_usuarios=1)

	def filtrar_por_username(self,username):
		return self.filter(canalusuario__usuario__username=username)

class CanalManager(models.Manager):
	
	def get_queryset(self,*args,**kwargs):
		return CanalQuerySet(self.model, using=self._db)

	def filtrar_ms_por_privado(self,username_a,username_b):
		return self.get_queryset().solo_dos().filtrar_por_username(username_a).filtrar_por_username(username_b)


	def canal_usuario_actual(self, user):
		qs = self.get_queryset().solo_uno().filtrar_por_username(user.username)
		if qs.exists():
			return qs.order_by("tiempo").first,False

		canal_obj = Canal.objects.create()
		CanalUsuario.objects.create(usuario=user, canal=canal_obj)
		return canal_obj, True

	def obtener_crear_canal_mensaje(self,username_a,username_b):
		qs = self.filtrar_ms_por_privado(username_a,username_b)
		if qs.exists():
			return qs.order_by("tiempo").first(), False

		User = apps.get_model("auth",model_name="User")
		usuario_a, usuario_b = None, None

		try:
			usuario_a = User.objects.get(username=username_a)

		except User.DoesNotExits:
			return None, False
		
		try:
			usuario_b = User.objects.get(username=username_b)

		except User.DoesNotExits:
			return None, False

		if usuario_a == None or usuario_b == None:
			return None, False

		obj_canal = Canal.objects.create()
		User = apps.get_model("auth", model_name='User')
		canal_usuario_a = CanalUsuario(usuario=User.objects.get(username=username_a),canal=obj_canal)
		canal_usuario_b = CanalUsuario(usuario=User.objects.get(username=username_b),canal=obj_canal)
		CanalUsuario.objects.bulk_create([canal_usuario_a,canal_usuario_b])
		return obj_canal,True

class Canal(ModelBase):
	usuarios = models.ManyToManyField(User,blank = True, through=CanalUsuario)
	objects = CanalManager()













app/templates/Buscar.html
{% extends 'layout.html' %}

{% block content %}
{% load static %}

<style type="text/css">
    
body{
   background:  #dedede;
}

</style>


<!-- herencia de template -->
<nav class="navbar navbar-expand-lg navbar-light  fixed-top " style="background:#ffffff;box-shadow:0px 0px 5px 2px #a0a0a0;">
  <div class="container-fluid">
    <a class="navbar-brand " href="{% url 'inicio' %}"><img src="../static/img/Fox.png" style="width:40px;height: 40px;">
    </a>
    <p style="font-family: forte;" class="display-6">FaceFox</p>  
    
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarText">
      <ul class="navbar-nav mx-auto mb-2 mb-lg-0 justify-content-end">
        <!--
        <li class="nav-item">
          <a class="nav-link" href="#">Features</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Pricing</a>
        </li>
    -->
      </ul>

      <span class="navbar-text">
        <a href="{% url 'profile' request.user %}" class="nav-link"> <img src="../static/img/miPerfil.png" style="width:25px;height: 25px; "></a>
      </span>
       <span class="navbar-text">
        <a href="" class="nav-link"> <img src="../static/img/notificacion.png" style="width:25px;height: 25px; "></a>
      </span>
       
      <span class="navbar-text">
        <a href="{% url 'logout' %}" class="nav-link"> <img src="../static/img/salir.png" style="width:25px;height: 22px; "></a>
      </span>

    </div>
  </div>
</nav>


<div  class="container mt-3" >
    <div class="row d-flex justify-content-center mt-5">
        <div id="" class="col-12 col-md-8  " >
            <div class=" border m-5" style="background: white;border-radius: 10px;box-shadow: 0px 0px 5px 2px #a0a0a0;" >



            <div class="m-3" >
                <form class="d-flex form-group" action="{% url 'Busqueda' %}" >{% csrf_token %}
              <input class="form-control me-2" type="text" placeholder="Busqueda" aria-label="Search" id="buscar" name="Busqueda" >
              <button class="btn btn-outline-primary" for="busqueda" type="submit">Buscar</button>
            </form>

            </div>
                

           
          
           
            </div>
            
        </div>
    </div>
    <!-- End Center -->
</div>

{% endblock content %}

app/templates/busqueda.html
{% extends 'layout.html' %}

{% block content %}
{% load static %}

<style type="text/css">
    
body{
   background:  #dedede;
}

</style>


<!-- herencia de template -->
<nav class="navbar navbar-expand-lg navbar-light  fixed-top " style="background:#ffffff;box-shadow:0px 0px 5px 2px #a0a0a0;">
  <div class="container-fluid">
    <a class="navbar-brand " href="{% url 'inicio' %}"><img src="../static/img/Fox.png" style="width:40px;height: 40px;">
    </a>
    <p style="font-family: forte;" class="display-6">FaceFox</p>  

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarText">
      <ul class="navbar-nav mx-auto mb-2 mb-lg-0 justify-content-end">
        <!--
        <li class="nav-item">
          <a class="nav-link" href="#">Features</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Pricing</a>
        </li>
    -->
      </ul>

      <span class="navbar-text">
        <a href="{% url 'profile' request.user %}" class="nav-link"> <img src="../static/img/miPerfil.png" style="width:25px;height: 25px; "></a>
      </span>
       <span class="navbar-text">
        <a href="" class="nav-link"> <img src="../static/img/notificacion.png" style="width:25px;height: 25px; "></a>
      </span>
       
      <span class="navbar-text">
        <a href="{% url 'logout' %}" class="nav-link"> <img src="../static/img/salir.png" style="width:25px;height: 22px; "></a>
      </span>

    </div>
  </div>
</nav>


<div  class="container">
    <div class="row d-flex justify-content-center mt-5">
        <div id="" class="col-12 col-md-8  ">
            <div class=" border mt-5"  >





            <div class="m-3 p-3" style="background: white;border-radius: 10px;box-shadow: 0px 0px 5px 2px #a0a0a0;">
                <form class="d-flex" action="{% url 'Busqueda' %}" >{% csrf_token %}
              <input class="form-control me-2" type="text" placeholder="Busqueda" aria-label="Search" id="buscar" name="Busqueda" >
              <button class="btn btn-outline-primary" for="busqueda" type="submit">Buscar</button>
            </form>

            </div>
                

        




 {% for usuario in user %}
           <div  class="border mt-3 " style="background: #ffffff; border-radius: 10px; box-shadow: 0px 0px 5px 2px #a0a0a0;">
            <div class="d-flex m-3" >
                <div class="col-xs rounded-circle" >
                    <!-- Image form -->
                    <img src="{{usuario.profile.image.url}} " style="width:100px;border-radius: 50%;" alt=""
                        class="m-3">
                    <!-- Formulario -->
                </div>
                <div>
                  <p>

                    <a href="{% url 'profile' usuario %}" class="text-dark nav-link text-center" style="display:inline;display:block;">@{{usuario.username}} </a>
                  </p>
                     <p class="text-center" style="display:inline-block;">{{usuario.profile.bio}}</p>
                </div>

            </div>
            <div class="d-flex justify-content-center mt-2">
            </div>
        </div>
            {% endfor %}





           
          
           
            </div>
            
        </div>
    </div>
    <!-- End Center -->
</div>

{% endblock content %}

app/templates/editar.html
{% extends 'layout.html' %}

{% block content %}
{% load static %}

<style type="text/css">
    
body{
   background:  #dedede;
}
.x{
   
    margin-top: 20px;
    padding:  8px;
    
   
    width:20%;
    border-radius: 15px;
    text-align: center;
    
    
}

input[type="file"]{
    width:0.1px;
    height: 0.1px;
    opacity: 0;

}

</style>


<!-- herencia de template -->
<nav class="navbar navbar-expand-lg navbar-light  fixed-top " style="background:#ffffff;box-shadow:0px 0px 5px 2px #a0a0a0;">
  <div class="container-fluid">
    <a class="navbar-brand " href="{% url 'inicio' %}"><img src="../static/img/Fox.png" style="width:40px;height: 40px;">
    </a>
    <p style="font-family: forte;" class="display-6">FaceFox</p>  
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarText">
      <ul class="navbar-nav mx-auto mb-2 mb-lg-0 justify-content-end">
        <!--
        <li class="nav-item">
          <a class="nav-link" href="#">Features</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Pricing</a>
        </li>
    -->
      </ul>

      <span class="navbar-text">
        <a href="{% url 'profile' request.user %}" class="nav-link"> <img src="../static/img/miPerfil.png" style="width:25px;height: 25px; "></a>
      </span>
       <span class="navbar-text">
        <a href="" class="nav-link"> <img src="../static/img/notificacion.png" style="width:25px;height: 25px; "></a>
      </span>
       
      <span class="navbar-text">
        <a href="{% url 'logout' %}" class="nav-link"> <img src="../static/img/salir.png" style="width:25px;height: 22px; "></a>
      </span>

    </div>
  </div>
</nav>


<div  class="container">
    <div class="row d-flex justify-content-center mt-5">
        <div id="" class="col-12 col-md-8 col-lg-6 ">
            <div class=" border mt-5" style="background:#ffffff;box-shadow:0px 0px 5px 2px #a0a0a0;">
                

                <!-- Formulario -->
        <form class=" mx-auto mt-5  " method="post" enctype="multipart/form-data">
                    {% csrf_token %}
              
                <p class="m-3">
                    <!-- Image form -->
                    <img src="{{user.profile.image.url}}" alt="" class=""  style="width:100px;border-radius: 50%;">


                </p>

            <div class="form-group m-3 ">     
                <input type="text" class="form-control" placeholder="Nombre" id="nombre" name="username" >
            </div>

            <div class="form-group m-3">    
                <input type="text" class="form-control" placeholder="Biografia" id="nombre" name="bio" >
            </div>
            <div class="form-group m-3">  
                <input type="number" class="form-control" placeholder="telefono" id="nombre" name="telefono" >
            </div>
             <div class="form-group m-3">    
                <input type="text" class="form-control" placeholder="Pais" id="nombre" name="pais" >
            </div>
             <div class="form-group m-3">    
                <input type="text" class="form-control" placeholder="Ciudad" id="nombre" name="city" >
            </div>
                 
              <div class="mt-3  mx-auto" >
                 <input type="file" name="image" class=" border mx-auto" id="boton" placeholder="Foto" aria-label='Archivo'>
                 <label class="x mt-3" for="boton">
                     <img style="width:25px;height: 25px; " src="../static/img/subirFoto.png">
                 </label>
                 <span>AGREGAR IMAGEN</span>
            </div>  
                    

                  <button type="submit" class="btn btn-outline-success m-3 text-center " style="width: 95%; font-size: 1.1rem; font-weight:bold;">Guardar</button>   
                </form>
                <!-- Formulario -->

            </div>
        </div>
    </div>
    <!-- End Center -->
</div>

{% endblock content %}

app/templates/layout.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title></title>
	<link rel="stylesheet" type="text/css" href="{ static 'css/bootstrap.css'}">
  
	<link rel="stylesheet" type="text/css" href="../static/css/bootstrap.min.css">
	<link rel="stylesheet" type="text/css" href="../static/css/style.css">
	<link rel="stylesheet" type="text/css" href="../static/css/animate.css">




</head>
<body >

{% block content %}



{% endblock content %}

<script type="text/javascript" src="../static/js/bootstrap.bundle.js"></script>


</body>
</html>

app/templates/login.html
{% extends 'layout.html' %}
{% block content %}
{% load humanize %}
{% load static %}

<style type="text/css">
    
  
body{
	background: #dedede;
}

</style>



<div class="container " >
	<div class="row d-flex justify-content-center mt-5">
		
		<div class=" col-12 col-md-8 col-lg-6 "  style="  background: rgba(255,255,255,1 );box-shadow: 0px 0px 5px 2px #a0a0a0;">
			
		
			
			  <form method="post" class="mx-auto " >{% csrf_token %}
			  		<p class="display-2  mt-5 text-center" id="fax"  style="font-family:fonte">
			  			<img src="../static/img/Fox.png" id="img" style="width:150px;height: 150px;">   FaceFox</p>


			  			 {% if form.errors %} 


			  			 <style type="text/css">
			  			 	
			  			 		#img{
			  			 			display: none;
			  			 		}
			  			 		#fax{
			  			 				display: none;
			  			 		}

			  			 </style>


			  			 <p class="display-2  mt-5 text-center wow bounceIn  animated" style="font-family:fonte;color:#b50a10;visibility: visible; animation-delay: .30s; animation-name: bounceIn;" data-wow-delay="0.30s">
			  			<img src="../static/img/FoxRojo.png"class="wow bounceIn  animated" style="width:150px;height: 150px; visibility: visible; animation-delay: .30s; animation-name: bounceIn; color: #b50a10; "  data-wow-delay="0.30s" >   FaceFox</p>
            
            		{% endif %}

            <div class="form-group">
				
				<input type="text" class="form-control" placeholder="Nombre" id="nombre" name="username" >
			</div>
			<div class="form-group mt-3">
				
				<input type="password" class="form-control" placeholder="Contraseña" id="pwd" name="password" >
			</div>

              
  
				<div class="mt-3 mb-5">

				 {% if form.errors %}  
			         
			          	<p class="text-center font-weight-bold mb-3  wow bounceIn  animated pt-2 pb-2" data-wow-delay="0.30s" style="   visibility: visible; animation-delay: .30s; animation-name: bounceIn; color: #b50a10; ">Nombre o Contraseña Incorrectos</p>

			     
                    
             
            {% endif %}
                	 <button type="submit" class="btn btn-outline-success  " style="width: 49%; font-size: 1.1rem; font-weight:bold;">Iniciar Sesión</button>
                	 <a href="{% url 'register' %}" class="btn btn-outline-primary  " style="width: 49%; font-size: 1.1rem; font-weight:bold;">Registrarse</a>
                </div>
           
        </form>

		</div>
	</div>
</div>





{% endblock content %}

app/templates/mensaje.html
{% extends 'layout.html' %}

{% block content %}
{% load static %}


<nav class="navbar navbar-expand-lg navbar-light  fixed-top " style="background:#ffffff; box-shadow:0px 0px 5px 2px #a0a0a0;position:block">

  <div class="container-fluid">
    <a class="navbar-brand " href="{% url 'inicio' %}"><img src="../static/img/Fox.png" style="width:40px;height: 40px; margin-right: 5px;"></a>
      <p style="font-family: forte;" class="display-6">FaceFox</p>      
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
   
    <div class="collapse navbar-collapse m-2" id="navbarText">
        
      <ul class="navbar-nav mx-auto mb-2 mb-lg-0 justify-content-end">
      	<!--
        <li class="nav-item">
          <a class="nav-link" href="#">Features</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Pricing</a>
        </li>
    -->
      </ul>

      <span class="navbar-text">
        <a href="{% url 'profile' request.user %}" class="nav-link"> <img src="../static/img/miPerfil.png" style="width:25px;height: 25px; "></a>
      </span>
      <span class="navbar-text">
        <a href="{% url 'Buscar' %}" class="nav-link"> <img src="../static/img/buscador.png" style="width:25px;height: 25px; "></a>
      </span>
       
       <span class="navbar-text">
        <a href="" class="nav-link"> <img src="../static/img/notificacion.png" style="width:25px;height: 25px; "></a>
      </span>
      
       
      <span class="navbar-text">
      	<a href="{% url 'logout' %}" class="nav-link"> <img src="../static/img/salir.png" style="width:25px;height: 22px; "></a>
      </span>

    </div>
  </div>
</nav>





<div class="container mt-5 mt-5" style="margin-top: 300px;">
	<div class="row d-flex justify-content-center mt-5 mt-5">
		
		<div class=" col-12 col-md-8 p-5 mt-5"  style="  background: rgba(255,255,255,1 );box-shadow: 0px 0px 5px 2px #a0a0a0;">


<div class="mt-5" >

  
  




              {% for mensaje in object.canalmensaje_set.all %}
          
              {% if request.user == mensaje.usuario %}
              
              <div id="" style="background-color: rgb(7, 161, 238); color: rgb(255, 255, 255);margin-left: 25%; margin-top: 5px; padding: 5px; border-radius: 20px 0px 20px 20px;">

                <small>@{{mensaje.usuario}}</small>
                <p class="lead font-weight-bold">{{mensaje.texto}}</p>
                <small style="text-align: left;">{{mensaje.tiempo}}</small>

              </div>

              {% else  %}
              
              <div id="" style="background-color: rgb(58, 59, 59); color: rgb(255, 255, 255);margin-right: 25%; margin-top: 5px; padding: 5px; border-radius: 0px 20px 20px 20px;">

                <small>@{{mensaje.usuario}}</small>
                <p class="lead font-weight-bold">{{mensaje.texto}}</p>
                <small style="text-align: left;">{{mensaje.tiempo}}</small>

              </div>


              {% endif %}
            
            
            
            
            
            {% endfor %}
              
          </div>


<div style="position: unset;">

  <form id="form_submit" action="{{ request.path }}" method="POST">
    {% csrf_token %}
  
    {{form.as_p}}
  
    <button type="submit" class="btn btn-primary p-2 mx-auto" style="width:100%;border-radius: 10px;">
      PUBLICAR
    </button>
    
  </form>
</div>
		</div>
	</div>
</div>
























<!-- ********** javascript ***************** -->
<!-- 
<script>

  const MsgForm = document.getElementById("form_submit")
  const MsgContainer = document.getElementById("contenedor_mensaje")
  
  MsgForm.addEventListener("submit",(event)=>{

    event.preventDefault()
    const targetDate = event.target
    const formData = new FormData(targetDate)

    const xhr = new XMLHttpRequest()

    const endpoint = MsgForm.getAttribute("action")
    const method = MsgForm.getAttribute("method")
    xhr.open(method,endpoint)

    xhr.responseType = 'json'

    xhr.setRequestHeader("HTTP_X_REQUESTED_WITH","XMLHttpRequest")
    xhr.setRequestHeader("X-Requested-With","XMLHttpRequest")

    xhr.onload = () =>{

      console.log(xhr.status,xhr.response)
      let respuestaData=0;
      if(xhr.status === 500){
        respuestaData = xhr.response
        let actualMensaje = MsgContainer.innerHTML
        actualMensaje += `<div class=''><b>${respuestaData.username}
          </b><p>${respuestaData.mensaje}
            </p></div>`
        
            MsgContainer.innerHTML = actualMensaje
            MsgForm.reset()
      }else if(xhr.status === 400){
console.log(xhr.response)
      }else{
        alert('ocurrio un error')
      }

    }

    xhr.send(formData)

  })



</script> -->




{% endblock content %}

app/templates/register.html
{% extends 'layout.html' %}
{% load static %}
{% block content %}



<style type="text/css">
    

body{
    background: #dedede;
}


</style>


    <div class="container">
        <div class="row d-flex justify-content-center mt-5">
            
  



  
        <form class=" col-12 col-md-8 col-lg-6 border" style="background:#ffffff; box-shadow: 0px 0px 5px 2px #a0a0a0; "  method="post">
            {% csrf_token %}
            
            <p class="display-2  mt-5 text-center" id="fax" style="font-family:fonte"><img id="img" src="../static/img/Fox.png" style="width:150px;height: 150px;">  FaceFox</p>

             {% if form.errors %} 


                         <style type="text/css">
                            
                                #img{
                                    display: none;
                                }
                                #fax{
                                    display: none;
                                }

                         </style>


                         <p class="display-2  mt-5 text-center" style="font-family:fonte;color:#b50a10;">
                        <img src="../static/img/FoxRojo.png" style="width:150px;height: 150px;">   FaceFox</p>
            
                    {% endif %}

            <div class="form-group mt-4">
                
                <input type="text" class="form-control" placeholder="Nombre" id="nombre" name="username" >
                
            </div>
            <div class="form-group mt-3">
                
                <input type="password" class="form-control" placeholder="Contraseña" id="pwd" name="password1" >
            </div>
            <div class="form-group mt-3">
                <input type="password" class="form-control" placeholder=" Confirmar Contraseña" id="pwd" name="password2" >
            </div>
         
            {% if form.errors %}             
                    <p class="text-center font-weight-bold mt-3 text-danger wow bounceIn  animated" data-wow-delay="0.30s" style="   visibility: visible; animation-delay: .30s; animation-name: bounceIn; ">Registro Incorrecto</p>
            {% endif %}

            <div class="mt-3 mb-5">
                     <button type="submit" class="btn btn-outline-success  " style="width: 100%; font-size: 1.1rem; font-weight:bold;">Registrar</button>      
            </div>


                <div class="footer text-center m-3">
            <a href="{% url 'login' %}">¿Ya tienes una cuenta? Login</a>
        </div>

   </form>





        

    </div>
</div>

    {% endblock content %}